/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    api(project(":caniuse-api"))
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.neo4j.driver.neo4j.java.driver.slim)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.slf4j.slf4j.nop)
    testImplementation(libs.org.testcontainers.junit.jupiter)
    testImplementation(libs.org.testcontainers.neo4j)
}

description = "caniuse-neo4j-detection"
