/*
 * This file was generated by the Gradle 'init' task.
 */

import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm")
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "org.neo4j"
version = "1.1.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["kotlin"])
    }
}

tasks.withType<JavaCompile> {
    enabled = false
}

tasks.withType<Javadoc> {
    enabled = false
}

sourceSets {
    main {
        kotlin {
            setSrcDirs(mutableSetOf(File("src/main/kotlin")))
        }
    }
    test {
        kotlin {
            setSrcDirs(mutableSetOf(File("src/test/kotlin")))
        }
    }
}

tasks.withType<KotlinCompile> {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_11)
    }
}
